FEATURE_FLAGS = {
2 " EMBEDDED_SUPERSET ": True ,
3 }
4
5 ENABLE_PROXY_FIX = True
6 SESSION_COOKIE_SAMESITE = None
7
8 PUBLIC_ROLE_LIKE_GAMMA = True
9 # AUTH_ROLE_PUBLIC = ’Gamma ’
10
11 WTF_CSRF_ENABLED = False
12 TALISMAN_ENABLED = False
13
14 HTTP_HEADERS = {’X-Frame - Options ’: ’ALLOWALL ’}
